controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  left_momentum_block_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: left_momentum_block_joint
    actuator: [ left_momentum_block_joint_motor ]
    search_velocity: 0.5
    threshold: 0.001
    pid: { p: 50, i: 0, d: 0, i_clamp_max: 0.5, i_clamp_min: 0, antiwindup: true }
  right_momentum_block_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: right_momentum_block_joint
    actuator: [ right_momentum_block_joint_motor ]
    search_velocity: 0.5
    threshold: 0.001
    pid: { p: 50, i: 0, d: 0, i_clamp_max: 0.5, i_clamp_min: 0, antiwindup: true }
  trigger_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: trigger_joint
    actuator: [ trigger_joint_motor ]
    search_velocity: 3.1415
    threshold: 0.2
    pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  cover_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: cover_joint
    actuator: [ cover_joint_motor ]
    search_velocity: 2
    threshold: 1e-2
    pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  chassis_controller:
    type: rm_chassis_controllers/BalanceController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 12.0
      vel_coeff: 0.0048
      power_offset: 0
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 8, i: 0, d: 4.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # BalanceController
    imu_name: "base_imu"
    m_w: 0.72
    m: 11.48
    m_b: 1.13
    i_w: 0.01683
    l: 0.0587
    y_b: 0.16
    z_b: 0.0468
    g: 9.8
    i_m: 0.1982
    wheel_radius: 0.125
    wheel_base: 0.42
    position_offset: 0.
    position_clear_threshold: 1.
    left:
      wheel_joint: "left_wheel_joint"
      block_joint: "left_momentum_block_joint"
    right:
      wheel_joint: "right_wheel_joint"
      block_joint: "right_momentum_block_joint"

    q: [ 0.5, 0.5, 40, 51, 51, 10, 0.2, 0.1, 1, 1 ]
    r: [ 0.5, 0.5, 0.002, 0.002 ]

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 7.5, i: 0, d: 0.3, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }
      k_chassis_vel: 0
    pitch:
      joint: "pitch_joint"
      pid: { p: 25.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
    chassis_vel:
      num_data: 20
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0, 0.0, 0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 1.0
      resistance_coff_qd_16: 1.5
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 5.0
      g: 9.81
      delay: 0.15
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      joint: "left_friction_wheel_joint"
      pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      joint: "right_friction_wheel_joint"
      pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 50.0, i: 0.0, d: 1.3, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 8
    push_qd_threshold: 0.90
    forward_push_threshold: 0.1
    exit_push_threshold: 0.1
    block_effort: 0.88
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.2
    anti_block_threshold: 0.1
    qd_15: 460.0
    qd_18: 500.0
    qd_30: 730.0
