rm_track:
  max_match_distance: 0.1
  max_storage_time: 2.0
  max_lost_time: 0.1
  filters:
    - type: height_filter
      basic_range: [ -0.6, 999.0 ]
      double_check_range: [ 0.5, 1.0 ]
    - type: distance_filter
      basic_range: [ 0., 999. ]
      double_check_range: [ 4.0, 6.0 ]
  selectors:
    - last_armor
    - same_id_armor
    - random_armor
  linear_kf:
    Q: [ 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0 ]
    R: [ 0.01, 0.01, 0.01 ]
