rm_manual:
  robot_type: "drone"
  supply_frame: "supply_frame"
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/controllers/shooter_controller/command"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 20
      expect_shoot_frequency_2: 20
      expect_shoot_frequency_3: 20
      burst_shoot_frequency: 20
      safe_shoot_frequency: 20
      heat_coeff: 8.0
      type: "ID1_17MM"
  detection_switch:
    fail_limit: 10
    service_name: "/detection_nodelet/status_switch"

  controllers_list:
    state_controllers:
      - controllers/joint_state_controller
      - controllers/robot_state_controller
    main_controllers:
      - controllers/orientation_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
    calibration_controllers:
      - controllers/trigger_calibration_controller
      - controllers/gimbal_calibration_controller

  gimbal_calibration:
    - start_controllers:
        - controllers/gimbal_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
      services_name:
        - /controllers/gimbal_calibration_controller/is_calibrated
  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/shooter_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated

  ui:
    trigger_change:
      - name: "chassis"
        config: { start_position: [ 400, 750 ], size: 15, width: 2, title: "chassis: " }
      - name: "target"
        config: { start_position: [ 400, 700 ], size: 15, width: 2, title: "target:  " }
      - name: "exposure"
        config: { start_position: [ 400, 650 ], size: 15, width: 2, title: "exposure:" }
    time_change:
      - name: "capacitor"
        config: { start_position: [ 900, 100 ], size: 15, width: 2, delay: 0.5 }
    fixed:
      - name: "2m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 925, 435 ], end_position: [ 995, 435 ] }
      - name: "3m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 935, 420 ], end_position: [ 985, 420 ] }
      - name: "5m"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 948, 400 ], end_position: [ 972, 400 ] }
      - name: "mid"
        config: { type: "line", width: 2, color: "yellow",
                  start_position: [ 960, 400 ], end_position: [ 960, 540 ] }
    flash:
      - name: "spin"
        config: { start_position: [ 850, 750 ], size: 20, width: 2,
                  color: "yellow", content: "please spin!!", delay: 0.8 }
      - name: "cover"
        config: { start_position: [ 830, 700 ], size: 25, width: 2,
                  color: "green", content: "cover open!!", delay: 0.8 }
      - name: "armor0"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor1"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor2"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
      - name: "armor3"
        config: { type: "circle", width: 3, radius: 50, color: "yellow", delay: 0.75 }
